
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'XFLNetwork_Example' do
  pod 'XFLNetwork', :path => '../'

  target 'XFLNetwork_Tests' do
    inherit! :search_paths

    
  end
end
